# Setup
url: http://roshanca.com
author: Roshan Wu
title: 肉山·察
subtitle: just Roshan's blog

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:title
relative_permalinks: true

# Where things are
source: site
destination: ./_site
plugins: ./_plugins

# Markdown Processors
markdown: redcarpet
redcarpet:
  extensions: [autolink, smart, tables, strikethrough, superscript, with_toc_data, footnotes]

# Syntax highlighting
highlighter: pygments

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  style: :compressed

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: roshanca
branch: master
repo: blog
