encoding: utf-8
name: blog
url: http://roshanca.com
author: Roshan Wu
title: 肉山·察
subtitle: Just Roshan's blog
permalink: /:year/:title
source: site
destination: ./_site
plugins: ./_plugins
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough", "superscript", "with_toc_data"]


# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: roshanca
branch: master
repo: blog
